version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../tmp/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:6.6.1
    restart: always
    ports:
      - 5601:5601
